language: node_js
sudo: required
cache:
   directories:
     - node_modules
node_js:
  - 8
before_install:
  - export NODE_ENV=production
  - npm install -g node-gyp
before_script:
  - npm install
script:
  - npm run lint
  - npm run test